apiVersion: apps/v1
kind: Deployment
metadata:
  name: testoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: image2
          image: yassine2023/yassinetest:latest
          ports:
            - containerPort: 1122
---
apiVersion: v1
kind: Service
metadata:
  name: testoo
spec:
  selector:
    app: test1
  ports:
    - protocol: TCP
      port: 1122
      targetPort: 1122
  type: LoadBalancer
